# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bareun/dict_common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'bareun/dict_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62\x61reun/dict_common.proto\x12\x06\x62\x61reun\"\xaf\x01\n\x07\x44ictSet\x12\x30\n\x05items\x18\x01 \x03(\x0b\x32\x1a.bareun.DictSet.ItemsEntryR\x05items\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x10.bareun.DictTypeR\x04type\x12\x12\n\x04name\x18\n \x01(\tR\x04name\x1a\x38\n\nItemsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x05R\x05value:\x02\x38\x01*B\n\x08\x44ictType\x12\x0f\n\x0bTOKEN_INDEX\x10\x00\x12\r\n\tWORD_LIST\x10\x01\x12\x16\n\x12WORD_LIST_COMPOUND\x10\x02\x42V\n\x10\x61i.bareun.protosB\x15\x44ictionaryCommonProtoP\x01Z)bareun.ai/lang/bareun/genproto/bareun;svcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bareun.dict_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020ai.bareun.protosB\025DictionaryCommonProtoP\001Z)bareun.ai/lang/bareun/genproto/bareun;svc'
  _globals['_DICTSET_ITEMSENTRY']._loaded_options = None
  _globals['_DICTSET_ITEMSENTRY']._serialized_options = b'8\001'
  _globals['_DICTTYPE']._serialized_start=214
  _globals['_DICTTYPE']._serialized_end=280
  _globals['_DICTSET']._serialized_start=37
  _globals['_DICTSET']._serialized_end=212
  _globals['_DICTSET_ITEMSENTRY']._serialized_start=156
  _globals['_DICTSET_ITEMSENTRY']._serialized_end=212
# @@protoc_insertion_point(module_scope)
