# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: bareun/language_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import bareun.language_service_pb2 as bareun_dot_language__service__pb2


class LanguageService(Protocol):
    async def analyze_syntax(self, request: bareun_dot_language__service__pb2.AnalyzeSyntaxRequest, ctx: RequestContext) -> bareun_dot_language__service__pb2.AnalyzeSyntaxResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def analyze_syntax_list(self, request: bareun_dot_language__service__pb2.AnalyzeSyntaxListRequest, ctx: RequestContext) -> bareun_dot_language__service__pb2.AnalyzeSyntaxListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def tokenize(self, request: bareun_dot_language__service__pb2.TokenizeRequest, ctx: RequestContext) -> bareun_dot_language__service__pb2.TokenizeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class LanguageServiceASGIApplication(ConnectASGIApplication[LanguageService]):
    def __init__(self, service: LanguageService | AsyncGenerator[LanguageService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/bareun.LanguageService/AnalyzeSyntax": Endpoint.unary(
                    method=MethodInfo(
                        name="AnalyzeSyntax",
                        service_name="bareun.LanguageService",
                        input=bareun_dot_language__service__pb2.AnalyzeSyntaxRequest,
                        output=bareun_dot_language__service__pb2.AnalyzeSyntaxResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.analyze_syntax,
                ),
                "/bareun.LanguageService/AnalyzeSyntaxList": Endpoint.unary(
                    method=MethodInfo(
                        name="AnalyzeSyntaxList",
                        service_name="bareun.LanguageService",
                        input=bareun_dot_language__service__pb2.AnalyzeSyntaxListRequest,
                        output=bareun_dot_language__service__pb2.AnalyzeSyntaxListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.analyze_syntax_list,
                ),
                "/bareun.LanguageService/Tokenize": Endpoint.unary(
                    method=MethodInfo(
                        name="Tokenize",
                        service_name="bareun.LanguageService",
                        input=bareun_dot_language__service__pb2.TokenizeRequest,
                        output=bareun_dot_language__service__pb2.TokenizeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.tokenize,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bareun.LanguageService"


class LanguageServiceClient(ConnectClient):
    async def analyze_syntax(
        self,
        request: bareun_dot_language__service__pb2.AnalyzeSyntaxRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_language__service__pb2.AnalyzeSyntaxResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AnalyzeSyntax",
                service_name="bareun.LanguageService",
                input=bareun_dot_language__service__pb2.AnalyzeSyntaxRequest,
                output=bareun_dot_language__service__pb2.AnalyzeSyntaxResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def analyze_syntax_list(
        self,
        request: bareun_dot_language__service__pb2.AnalyzeSyntaxListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_language__service__pb2.AnalyzeSyntaxListResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AnalyzeSyntaxList",
                service_name="bareun.LanguageService",
                input=bareun_dot_language__service__pb2.AnalyzeSyntaxListRequest,
                output=bareun_dot_language__service__pb2.AnalyzeSyntaxListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def tokenize(
        self,
        request: bareun_dot_language__service__pb2.TokenizeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_language__service__pb2.TokenizeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Tokenize",
                service_name="bareun.LanguageService",
                input=bareun_dot_language__service__pb2.TokenizeRequest,
                output=bareun_dot_language__service__pb2.TokenizeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class LanguageServiceSync(Protocol):
    def analyze_syntax(self, request: bareun_dot_language__service__pb2.AnalyzeSyntaxRequest, ctx: RequestContext) -> bareun_dot_language__service__pb2.AnalyzeSyntaxResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def analyze_syntax_list(self, request: bareun_dot_language__service__pb2.AnalyzeSyntaxListRequest, ctx: RequestContext) -> bareun_dot_language__service__pb2.AnalyzeSyntaxListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def tokenize(self, request: bareun_dot_language__service__pb2.TokenizeRequest, ctx: RequestContext) -> bareun_dot_language__service__pb2.TokenizeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class LanguageServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: LanguageServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/bareun.LanguageService/AnalyzeSyntax": EndpointSync.unary(
                    method=MethodInfo(
                        name="AnalyzeSyntax",
                        service_name="bareun.LanguageService",
                        input=bareun_dot_language__service__pb2.AnalyzeSyntaxRequest,
                        output=bareun_dot_language__service__pb2.AnalyzeSyntaxResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.analyze_syntax,
                ),
                "/bareun.LanguageService/AnalyzeSyntaxList": EndpointSync.unary(
                    method=MethodInfo(
                        name="AnalyzeSyntaxList",
                        service_name="bareun.LanguageService",
                        input=bareun_dot_language__service__pb2.AnalyzeSyntaxListRequest,
                        output=bareun_dot_language__service__pb2.AnalyzeSyntaxListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.analyze_syntax_list,
                ),
                "/bareun.LanguageService/Tokenize": EndpointSync.unary(
                    method=MethodInfo(
                        name="Tokenize",
                        service_name="bareun.LanguageService",
                        input=bareun_dot_language__service__pb2.TokenizeRequest,
                        output=bareun_dot_language__service__pb2.TokenizeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.tokenize,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bareun.LanguageService"


class LanguageServiceClientSync(ConnectClientSync):
    def analyze_syntax(
        self,
        request: bareun_dot_language__service__pb2.AnalyzeSyntaxRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_language__service__pb2.AnalyzeSyntaxResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AnalyzeSyntax",
                service_name="bareun.LanguageService",
                input=bareun_dot_language__service__pb2.AnalyzeSyntaxRequest,
                output=bareun_dot_language__service__pb2.AnalyzeSyntaxResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def analyze_syntax_list(
        self,
        request: bareun_dot_language__service__pb2.AnalyzeSyntaxListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_language__service__pb2.AnalyzeSyntaxListResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AnalyzeSyntaxList",
                service_name="bareun.LanguageService",
                input=bareun_dot_language__service__pb2.AnalyzeSyntaxListRequest,
                output=bareun_dot_language__service__pb2.AnalyzeSyntaxListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def tokenize(
        self,
        request: bareun_dot_language__service__pb2.TokenizeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_language__service__pb2.TokenizeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Tokenize",
                service_name="bareun.LanguageService",
                input=bareun_dot_language__service__pb2.TokenizeRequest,
                output=bareun_dot_language__service__pb2.TokenizeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


