# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: bareun/custom_dict.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import bareun.custom_dict_pb2 as bareun_dot_custom__dict__pb2
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CustomDictionaryService(Protocol):
    async def get_custom_dictionary_list(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> bareun_dot_custom__dict__pb2.GetCustomDictionaryListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_custom_dictionary(self, request: bareun_dot_custom__dict__pb2.GetCustomDictionaryRequest, ctx: RequestContext) -> bareun_dot_custom__dict__pb2.GetCustomDictionaryResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_custom_dictionary(self, request: bareun_dot_custom__dict__pb2.UpdateCustomDictionaryRequest, ctx: RequestContext) -> bareun_dot_custom__dict__pb2.UpdateCustomDictionaryResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def remove_custom_dictionaries(self, request: bareun_dot_custom__dict__pb2.RemoveCustomDictionariesRequest, ctx: RequestContext) -> bareun_dot_custom__dict__pb2.RemoveCustomDictionariesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def check_conflict(self, request: bareun_dot_custom__dict__pb2.CheckConflictRequest, ctx: RequestContext) -> bareun_dot_custom__dict__pb2.CheckConflictResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class CustomDictionaryServiceASGIApplication(ConnectASGIApplication[CustomDictionaryService]):
    def __init__(self, service: CustomDictionaryService | AsyncGenerator[CustomDictionaryService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/bareun.CustomDictionaryService/GetCustomDictionaryList": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCustomDictionaryList",
                        service_name="bareun.CustomDictionaryService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=bareun_dot_custom__dict__pb2.GetCustomDictionaryListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_custom_dictionary_list,
                ),
                "/bareun.CustomDictionaryService/GetCustomDictionary": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCustomDictionary",
                        service_name="bareun.CustomDictionaryService",
                        input=bareun_dot_custom__dict__pb2.GetCustomDictionaryRequest,
                        output=bareun_dot_custom__dict__pb2.GetCustomDictionaryResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_custom_dictionary,
                ),
                "/bareun.CustomDictionaryService/UpdateCustomDictionary": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateCustomDictionary",
                        service_name="bareun.CustomDictionaryService",
                        input=bareun_dot_custom__dict__pb2.UpdateCustomDictionaryRequest,
                        output=bareun_dot_custom__dict__pb2.UpdateCustomDictionaryResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_custom_dictionary,
                ),
                "/bareun.CustomDictionaryService/RemoveCustomDictionaries": Endpoint.unary(
                    method=MethodInfo(
                        name="RemoveCustomDictionaries",
                        service_name="bareun.CustomDictionaryService",
                        input=bareun_dot_custom__dict__pb2.RemoveCustomDictionariesRequest,
                        output=bareun_dot_custom__dict__pb2.RemoveCustomDictionariesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.remove_custom_dictionaries,
                ),
                "/bareun.CustomDictionaryService/CheckConflict": Endpoint.unary(
                    method=MethodInfo(
                        name="CheckConflict",
                        service_name="bareun.CustomDictionaryService",
                        input=bareun_dot_custom__dict__pb2.CheckConflictRequest,
                        output=bareun_dot_custom__dict__pb2.CheckConflictResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check_conflict,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bareun.CustomDictionaryService"


class CustomDictionaryServiceClient(ConnectClient):
    async def get_custom_dictionary_list(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_custom__dict__pb2.GetCustomDictionaryListResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCustomDictionaryList",
                service_name="bareun.CustomDictionaryService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=bareun_dot_custom__dict__pb2.GetCustomDictionaryListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_custom_dictionary(
        self,
        request: bareun_dot_custom__dict__pb2.GetCustomDictionaryRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_custom__dict__pb2.GetCustomDictionaryResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCustomDictionary",
                service_name="bareun.CustomDictionaryService",
                input=bareun_dot_custom__dict__pb2.GetCustomDictionaryRequest,
                output=bareun_dot_custom__dict__pb2.GetCustomDictionaryResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_custom_dictionary(
        self,
        request: bareun_dot_custom__dict__pb2.UpdateCustomDictionaryRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_custom__dict__pb2.UpdateCustomDictionaryResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateCustomDictionary",
                service_name="bareun.CustomDictionaryService",
                input=bareun_dot_custom__dict__pb2.UpdateCustomDictionaryRequest,
                output=bareun_dot_custom__dict__pb2.UpdateCustomDictionaryResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def remove_custom_dictionaries(
        self,
        request: bareun_dot_custom__dict__pb2.RemoveCustomDictionariesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_custom__dict__pb2.RemoveCustomDictionariesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RemoveCustomDictionaries",
                service_name="bareun.CustomDictionaryService",
                input=bareun_dot_custom__dict__pb2.RemoveCustomDictionariesRequest,
                output=bareun_dot_custom__dict__pb2.RemoveCustomDictionariesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def check_conflict(
        self,
        request: bareun_dot_custom__dict__pb2.CheckConflictRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_custom__dict__pb2.CheckConflictResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckConflict",
                service_name="bareun.CustomDictionaryService",
                input=bareun_dot_custom__dict__pb2.CheckConflictRequest,
                output=bareun_dot_custom__dict__pb2.CheckConflictResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class CustomDictionaryServiceSync(Protocol):
    def get_custom_dictionary_list(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> bareun_dot_custom__dict__pb2.GetCustomDictionaryListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_custom_dictionary(self, request: bareun_dot_custom__dict__pb2.GetCustomDictionaryRequest, ctx: RequestContext) -> bareun_dot_custom__dict__pb2.GetCustomDictionaryResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_custom_dictionary(self, request: bareun_dot_custom__dict__pb2.UpdateCustomDictionaryRequest, ctx: RequestContext) -> bareun_dot_custom__dict__pb2.UpdateCustomDictionaryResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def remove_custom_dictionaries(self, request: bareun_dot_custom__dict__pb2.RemoveCustomDictionariesRequest, ctx: RequestContext) -> bareun_dot_custom__dict__pb2.RemoveCustomDictionariesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def check_conflict(self, request: bareun_dot_custom__dict__pb2.CheckConflictRequest, ctx: RequestContext) -> bareun_dot_custom__dict__pb2.CheckConflictResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class CustomDictionaryServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: CustomDictionaryServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/bareun.CustomDictionaryService/GetCustomDictionaryList": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCustomDictionaryList",
                        service_name="bareun.CustomDictionaryService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=bareun_dot_custom__dict__pb2.GetCustomDictionaryListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_custom_dictionary_list,
                ),
                "/bareun.CustomDictionaryService/GetCustomDictionary": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCustomDictionary",
                        service_name="bareun.CustomDictionaryService",
                        input=bareun_dot_custom__dict__pb2.GetCustomDictionaryRequest,
                        output=bareun_dot_custom__dict__pb2.GetCustomDictionaryResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_custom_dictionary,
                ),
                "/bareun.CustomDictionaryService/UpdateCustomDictionary": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateCustomDictionary",
                        service_name="bareun.CustomDictionaryService",
                        input=bareun_dot_custom__dict__pb2.UpdateCustomDictionaryRequest,
                        output=bareun_dot_custom__dict__pb2.UpdateCustomDictionaryResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_custom_dictionary,
                ),
                "/bareun.CustomDictionaryService/RemoveCustomDictionaries": EndpointSync.unary(
                    method=MethodInfo(
                        name="RemoveCustomDictionaries",
                        service_name="bareun.CustomDictionaryService",
                        input=bareun_dot_custom__dict__pb2.RemoveCustomDictionariesRequest,
                        output=bareun_dot_custom__dict__pb2.RemoveCustomDictionariesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.remove_custom_dictionaries,
                ),
                "/bareun.CustomDictionaryService/CheckConflict": EndpointSync.unary(
                    method=MethodInfo(
                        name="CheckConflict",
                        service_name="bareun.CustomDictionaryService",
                        input=bareun_dot_custom__dict__pb2.CheckConflictRequest,
                        output=bareun_dot_custom__dict__pb2.CheckConflictResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check_conflict,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bareun.CustomDictionaryService"


class CustomDictionaryServiceClientSync(ConnectClientSync):
    def get_custom_dictionary_list(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_custom__dict__pb2.GetCustomDictionaryListResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCustomDictionaryList",
                service_name="bareun.CustomDictionaryService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=bareun_dot_custom__dict__pb2.GetCustomDictionaryListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_custom_dictionary(
        self,
        request: bareun_dot_custom__dict__pb2.GetCustomDictionaryRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_custom__dict__pb2.GetCustomDictionaryResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCustomDictionary",
                service_name="bareun.CustomDictionaryService",
                input=bareun_dot_custom__dict__pb2.GetCustomDictionaryRequest,
                output=bareun_dot_custom__dict__pb2.GetCustomDictionaryResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_custom_dictionary(
        self,
        request: bareun_dot_custom__dict__pb2.UpdateCustomDictionaryRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_custom__dict__pb2.UpdateCustomDictionaryResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateCustomDictionary",
                service_name="bareun.CustomDictionaryService",
                input=bareun_dot_custom__dict__pb2.UpdateCustomDictionaryRequest,
                output=bareun_dot_custom__dict__pb2.UpdateCustomDictionaryResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def remove_custom_dictionaries(
        self,
        request: bareun_dot_custom__dict__pb2.RemoveCustomDictionariesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_custom__dict__pb2.RemoveCustomDictionariesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RemoveCustomDictionaries",
                service_name="bareun.CustomDictionaryService",
                input=bareun_dot_custom__dict__pb2.RemoveCustomDictionariesRequest,
                output=bareun_dot_custom__dict__pb2.RemoveCustomDictionariesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def check_conflict(
        self,
        request: bareun_dot_custom__dict__pb2.CheckConflictRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_custom__dict__pb2.CheckConflictResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckConflict",
                service_name="bareun.CustomDictionaryService",
                input=bareun_dot_custom__dict__pb2.CheckConflictRequest,
                output=bareun_dot_custom__dict__pb2.CheckConflictResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


