# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: bareun/revision_service.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import bareun.revision_service_pb2 as bareun_dot_revision__service__pb2


class RevisionService(Protocol):
    async def correct_error(self, request: bareun_dot_revision__service__pb2.CorrectErrorRequest, ctx: RequestContext) -> bareun_dot_revision__service__pb2.CorrectErrorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def stream_correct_error(self, request: bareun_dot_revision__service__pb2.StreamCorrectErrorRequest, ctx: RequestContext) -> AsyncIterator[bareun_dot_revision__service__pb2.StreamCorrectErrorResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class RevisionServiceASGIApplication(ConnectASGIApplication[RevisionService]):
    def __init__(self, service: RevisionService | AsyncGenerator[RevisionService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/bareun.RevisionService/CorrectError": Endpoint.unary(
                    method=MethodInfo(
                        name="CorrectError",
                        service_name="bareun.RevisionService",
                        input=bareun_dot_revision__service__pb2.CorrectErrorRequest,
                        output=bareun_dot_revision__service__pb2.CorrectErrorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.correct_error,
                ),
                "/bareun.RevisionService/StreamCorrectError": Endpoint.server_stream(
                    method=MethodInfo(
                        name="StreamCorrectError",
                        service_name="bareun.RevisionService",
                        input=bareun_dot_revision__service__pb2.StreamCorrectErrorRequest,
                        output=bareun_dot_revision__service__pb2.StreamCorrectErrorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.stream_correct_error,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bareun.RevisionService"


class RevisionServiceClient(ConnectClient):
    async def correct_error(
        self,
        request: bareun_dot_revision__service__pb2.CorrectErrorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_revision__service__pb2.CorrectErrorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CorrectError",
                service_name="bareun.RevisionService",
                input=bareun_dot_revision__service__pb2.CorrectErrorRequest,
                output=bareun_dot_revision__service__pb2.CorrectErrorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def stream_correct_error(
        self,
        request: bareun_dot_revision__service__pb2.StreamCorrectErrorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[bareun_dot_revision__service__pb2.StreamCorrectErrorResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamCorrectError",
                service_name="bareun.RevisionService",
                input=bareun_dot_revision__service__pb2.StreamCorrectErrorRequest,
                output=bareun_dot_revision__service__pb2.StreamCorrectErrorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class RevisionServiceSync(Protocol):
    def correct_error(self, request: bareun_dot_revision__service__pb2.CorrectErrorRequest, ctx: RequestContext) -> bareun_dot_revision__service__pb2.CorrectErrorResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def stream_correct_error(self, request: bareun_dot_revision__service__pb2.StreamCorrectErrorRequest, ctx: RequestContext) -> Iterator[bareun_dot_revision__service__pb2.StreamCorrectErrorResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class RevisionServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: RevisionServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/bareun.RevisionService/CorrectError": EndpointSync.unary(
                    method=MethodInfo(
                        name="CorrectError",
                        service_name="bareun.RevisionService",
                        input=bareun_dot_revision__service__pb2.CorrectErrorRequest,
                        output=bareun_dot_revision__service__pb2.CorrectErrorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.correct_error,
                ),
                "/bareun.RevisionService/StreamCorrectError": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="StreamCorrectError",
                        service_name="bareun.RevisionService",
                        input=bareun_dot_revision__service__pb2.StreamCorrectErrorRequest,
                        output=bareun_dot_revision__service__pb2.StreamCorrectErrorResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.stream_correct_error,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bareun.RevisionService"


class RevisionServiceClientSync(ConnectClientSync):
    def correct_error(
        self,
        request: bareun_dot_revision__service__pb2.CorrectErrorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> bareun_dot_revision__service__pb2.CorrectErrorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CorrectError",
                service_name="bareun.RevisionService",
                input=bareun_dot_revision__service__pb2.CorrectErrorRequest,
                output=bareun_dot_revision__service__pb2.CorrectErrorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def stream_correct_error(
        self,
        request: bareun_dot_revision__service__pb2.StreamCorrectErrorRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[bareun_dot_revision__service__pb2.StreamCorrectErrorResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamCorrectError",
                service_name="bareun.RevisionService",
                input=bareun_dot_revision__service__pb2.StreamCorrectErrorRequest,
                output=bareun_dot_revision__service__pb2.StreamCorrectErrorResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


